//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWNSLWDTools {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BWNSLWDTools.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Air hang data has been written into tool successfully! 的本地化字符串。
        /// </summary>
        internal static string String_Air_hang_data_has_been_written_into_tool_successfully {
            get {
                return ResourceManager.GetString("String_Air_hang_data_has_been_written_into_tool_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to clear the data? 的本地化字符串。
        /// </summary>
        internal static string String_are_you_sure_to_clear_the_data {
            get {
                return ResourceManager.GetString("String_are_you_sure_to_clear_the_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete the file? 的本地化字符串。
        /// </summary>
        internal static string String_Are_you_sure_to_delete_the_file {
            get {
                return ResourceManager.GetString("String_Are_you_sure_to_delete_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AZI 的本地化字符串。
        /// </summary>
        internal static string String_AZI {
            get {
                return ResourceManager.GetString("String_AZI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootloader section size is less than firmware file size, upload firmware failed! 的本地化字符串。
        /// </summary>
        internal static string String_Bootloader_section_size_is_less_than_firmware_file_size_upload_firmware_failed {
            get {
                return ResourceManager.GetString("String_Bootloader_section_size_is_less_than_firmware_file_size_upload_firmware_fa" +
                        "iled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not stop Dsp! Error code is 的本地化字符串。
        /// </summary>
        internal static string String_Can_not_stop_Dsp_Error_code_is {
            get {
                return ResourceManager.GetString("String_Can_not_stop_Dsp_Error_code_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change length to 的本地化字符串。
        /// </summary>
        internal static string String_Change_length_to {
            get {
                return ResourceManager.GetString("String_Change_length_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Memory 的本地化字符串。
        /// </summary>
        internal static string String_Clear_Memory {
            get {
                return ResourceManager.GetString("String_Clear_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear memory successful! 的本地化字符串。
        /// </summary>
        internal static string String_Clear_memory_successful {
            get {
                return ResourceManager.GetString("String_Clear_memory_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Name 的本地化字符串。
        /// </summary>
        internal static string String_Company_Name {
            get {
                return ResourceManager.GetString("String_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIP 的本地化字符串。
        /// </summary>
        internal static string String_DIP {
            get {
                return ResourceManager.GetString("String_DIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to clear whole memory? 的本地化字符串。
        /// </summary>
        internal static string String_Do_you_want_to_clear_whole_memory {
            get {
                return ResourceManager.GetString("String_Do_you_want_to_clear_whole_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to clear memory! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_clear_memory {
            get {
                return ResourceManager.GetString("String_Fail_to_clear_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get basic parameters! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_get_basic_parameters {
            get {
                return ResourceManager.GetString("String_Fail_to_get_basic_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get bootloader section size, bootloader is stopped! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_get_bootloader_section_size_bootloader_is_stopped {
            get {
                return ResourceManager.GetString("String_Fail_to_get_bootloader_section_size_bootloader_is_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get fid data table! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_get_fid_data_table {
            get {
                return ResourceManager.GetString("String_Fail_to_get_fid_data_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get fid sequences! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_get_fid_sequences {
            get {
                return ResourceManager.GetString("String_Fail_to_get_fid_sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get firmware section size! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_get_firmware_section_size {
            get {
                return ResourceManager.GetString("String_Fail_to_get_firmware_section_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to get transmission Fid list in the tools settings! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_get_transmission_Fid_list_in_the_tools_settings {
            get {
                return ResourceManager.GetString("String_Fail_to_get_transmission_Fid_list_in_the_tools_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set basic parameters! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_set_basic_parameters {
            get {
                return ResourceManager.GetString("String_Fail_to_set_basic_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set board info, bootloader is stopped! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_set_board_info_bootloader_is_stopped {
            get {
                return ResourceManager.GetString("String_Fail_to_set_board_info_bootloader_is_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set fid data table! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_set_fid_data_table {
            get {
                return ResourceManager.GetString("String_Fail_to_set_fid_data_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set fid sequences! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_set_fid_sequences {
            get {
                return ResourceManager.GetString("String_Fail_to_set_fid_sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set firmware info, bootloader is stopped! 的本地化字符串。
        /// </summary>
        internal static string String_Fail_to_set_firmware_info_bootloader_is_stopped {
            get {
                return ResourceManager.GetString("String_Fail_to_set_firmware_info_bootloader_is_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to dump memory! 的本地化字符串。
        /// </summary>
        internal static string String_Failed_to_dump_memory {
            get {
                return ResourceManager.GetString("String_Failed_to_dump_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open firmware file! 的本地化字符串。
        /// </summary>
        internal static string String_Failed_to_open_firmware_file {
            get {
                return ResourceManager.GetString("String_Failed_to_open_firmware_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save to file! 的本地化字符串。
        /// </summary>
        internal static string String_Failed_to_save_to_file {
            get {
                return ResourceManager.GetString("String_Failed_to_save_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gamma 的本地化字符串。
        /// </summary>
        internal static string String_Gamma {
            get {
                return ResourceManager.GetString("String_Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get basic parameters successful! 的本地化字符串。
        /// </summary>
        internal static string String_Get_basic_parameters_successful {
            get {
                return ResourceManager.GetString("String_Get_basic_parameters_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get chip firmware section size successful! 的本地化字符串。
        /// </summary>
        internal static string String_Get_chip_firmware_section_size_successful {
            get {
                return ResourceManager.GetString("String_Get_chip_firmware_section_size_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get fid data table successful! 的本地化字符串。
        /// </summary>
        internal static string String_Get_fid_data_table_successful {
            get {
                return ResourceManager.GetString("String_Get_fid_data_table_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get fid sequences successful! 的本地化字符串。
        /// </summary>
        internal static string String_Get_fid_sequences_successful {
            get {
                return ResourceManager.GetString("String_Get_fid_sequences_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High/low inclination threshold 的本地化字符串。
        /// </summary>
        internal static string String_High_low_inclination_threshold {
            get {
                return ResourceManager.GetString("String_High_low_inclination_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTF 的本地化字符串。
        /// </summary>
        internal static string String_HTF {
            get {
                return ResourceManager.GetString("String_HTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INC 的本地化字符串。
        /// </summary>
        internal static string String_INC {
            get {
                return ResourceManager.GetString("String_INC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid air hang data! 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_air_hang_data {
            get {
                return ResourceManager.GetString("String_Invalid_air_hang_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid air hang data, data length is less than 64 bytes! 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_air_hang_data_data_length_is_less_than_64_bytes {
            get {
                return ResourceManager.GetString("String_Invalid_air_hang_data_data_length_is_less_than_64_bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input: End Time! 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_input_End_Time {
            get {
                return ResourceManager.GetString("String_Invalid_input_End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input: Max Temperature! 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_input_Max_Temperature {
            get {
                return ResourceManager.GetString("String_Invalid_input_Max_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input: Min Temperature! 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_input_Min_Temperature {
            get {
                return ResourceManager.GetString("String_Invalid_input_Min_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input: Start Time! 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_input_Start_Time {
            get {
                return ResourceManager.GetString("String_Invalid_input_Start_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid memory data 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_memroy_data {
            get {
                return ResourceManager.GetString("String_Invalid_memroy_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid memroy data packet: 的本地化字符串。
        /// </summary>
        internal static string String_Invalid_memroy_data_packet {
            get {
                return ResourceManager.GetString("String_Invalid_memroy_data_packet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master may not be connected, bootloader continues  ... 的本地化字符串。
        /// </summary>
        internal static string String_Master_may_not_be_connected_bootloader_continues {
            get {
                return ResourceManager.GetString("String_Master_may_not_be_connected_bootloader_continues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum data in a Fid is 18! 的本地化字符串。
        /// </summary>
        internal static string String_Maximum_data_in_a_Fid_is_18 {
            get {
                return ResourceManager.GetString("String_Maximum_data_in_a_Fid_is_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory dump finished successfully! 的本地化字符串。
        /// </summary>
        internal static string String_Memory_dump_finished_successfully {
            get {
                return ResourceManager.GetString("String_Memory_dump_finished_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MTF 的本地化字符串。
        /// </summary>
        internal static string String_MTF {
            get {
                return ResourceManager.GetString("String_MTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mwd 的本地化字符串。
        /// </summary>
        internal static string String_Mwd {
            get {
                return ResourceManager.GetString("String_Mwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NearBit 的本地化字符串。
        /// </summary>
        internal static string String_NearBit {
            get {
                return ResourceManager.GetString("String_NearBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a run number! 的本地化字符串。
        /// </summary>
        internal static string String_Please_select_a_run_number {
            get {
                return ResourceManager.GetString("String_Please_select_a_run_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select only one run number! 的本地化字符串。
        /// </summary>
        internal static string String_Please_select_only_one_run_number {
            get {
                return ResourceManager.GetString("String_Please_select_only_one_run_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Last Write Time 的本地化字符串。
        /// </summary>
        internal static string String_Product_Last_Write_Time {
            get {
                return ResourceManager.GetString("String_Product_Last_Write_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Name 的本地化字符串。
        /// </summary>
        internal static string String_Product_Name {
            get {
                return ResourceManager.GetString("String_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Version 的本地化字符串。
        /// </summary>
        internal static string String_Product_Version {
            get {
                return ResourceManager.GetString("String_Product_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PWD 的本地化字符串。
        /// </summary>
        internal static string String_Pwd {
            get {
                return ResourceManager.GetString("String_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading air hang data from tool successfully! 的本地化字符串。
        /// </summary>
        internal static string String_Reading_air_hang_data_from_tool_successfully {
            get {
                return ResourceManager.GetString("String_Reading_air_hang_data_from_tool_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading air hang data is failed! Error code is 的本地化字符串。
        /// </summary>
        internal static string String_Reading_air_hang_data_is_failed_Error_code_is {
            get {
                return ResourceManager.GetString("String_Reading_air_hang_data_is_failed_Error_code_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resistivity 的本地化字符串。
        /// </summary>
        internal static string String_Resistivity {
            get {
                return ResourceManager.GetString("String_Resistivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotating/non-rotating threshold 的本地化字符串。
        /// </summary>
        internal static string String_Rotating_nonrotating_threshold {
            get {
                return ResourceManager.GetString("String_Rotating_nonrotating_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPM 的本地化字符串。
        /// </summary>
        internal static string String_RPM {
            get {
                return ResourceManager.GetString("String_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to file successfully! 的本地化字符串。
        /// </summary>
        internal static string String_Save_to_file_successfully {
            get {
                return ResourceManager.GetString("String_Save_to_file_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial number should contain less than 16 characters! 的本地化字符串。
        /// </summary>
        internal static string String_Serial_number_should_contain_less_than_16_characters {
            get {
                return ResourceManager.GetString("String_Serial_number_should_contain_less_than_16_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set basic parameters successful! 的本地化字符串。
        /// </summary>
        internal static string String_Set_basic_parameters_successful {
            get {
                return ResourceManager.GetString("String_Set_basic_parameters_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set board info successful! Recycle power to run bootLoader. 的本地化字符串。
        /// </summary>
        internal static string String_Set_board_info_successful_Recycle_power_to_run_bootLoader {
            get {
                return ResourceManager.GetString("String_Set_board_info_successful_Recycle_power_to_run_bootLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set fid data table successful! 的本地化字符串。
        /// </summary>
        internal static string String_Set_fid_data_table_successful {
            get {
                return ResourceManager.GetString("String_Set_fid_data_table_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set fid sequences successful! 的本地化字符串。
        /// </summary>
        internal static string String_Set_fid_sequences_successful {
            get {
                return ResourceManager.GetString("String_Set_fid_sequences_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set firmware info successful! 的本地化字符串。
        /// </summary>
        internal static string String_Set_firmware_info_successful {
            get {
                return ResourceManager.GetString("String_Set_firmware_info_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get DirRes 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_DirRes_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_DirRes_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Density Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_DNDensity_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_DNDensity_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Neutron Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_DNNeutron_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_DNNeutron_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Sonic Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_DNSonic_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_DNSonic_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Gamma Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_Gamma_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_Gamma_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Mwd Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_Mwd_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_Mwd_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Gamma Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_NBGamma_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_NBGamma_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Res Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_NBRes_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_NBRes_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get ShortHop 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_NBShortHop_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_NBShortHop_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Status Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_NBStatus_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_NBStatus_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Pwd Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_Pwd_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_Pwd_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Get Res Data 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_Res_Data {
            get {
                return ResourceManager.GetString("String_Start_Get_Res_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Shorthop 的本地化字符串。
        /// </summary>
        internal static string String_Start_Get_RssShorthop {
            get {
                return ResourceManager.GetString("String_Start_Get_RssShorthop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get DirRes 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_DirRes_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_DirRes_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Density Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_DNDensity_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_DNDensity_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Neutron Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_DNNeutron_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_DNNeutron_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Sonic Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_DNSonic_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_DNSonic_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Gamma Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_Gamma_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_Gamma_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Mwd Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_Mwd_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_Mwd_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Gamma Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_NBGamma_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_NBGamma_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Res Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_NBRes_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_NBRes_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get ShortHop 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_NBShortHop_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_NBShortHop_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Status Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_NBStatus_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_NBStatus_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Pwd Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_Pwd_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_Pwd_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Get Res Data 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_Res_Data {
            get {
                return ResourceManager.GetString("String_Stop_Get_Res_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Shorthop 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Get_RssShorthop {
            get {
                return ResourceManager.GetString("String_Stop_Get_RssShorthop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Master is successful! 的本地化字符串。
        /// </summary>
        internal static string String_Stop_Master_is_successful {
            get {
                return ResourceManager.GetString("String_Stop_Master_is_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TEM 的本地化字符串。
        /// </summary>
        internal static string String_TEM {
            get {
                return ResourceManager.GetString("String_TEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TGF 的本地化字符串。
        /// </summary>
        internal static string String_TGF {
            get {
                return ResourceManager.GetString("String_TGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TMF 的本地化字符串。
        /// </summary>
        internal static string String_TMF {
            get {
                return ResourceManager.GetString("String_TMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write firmware file failed! 的本地化字符串。
        /// </summary>
        internal static string String_Write_firmware_file_failed {
            get {
                return ResourceManager.GetString("String_Write_firmware_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write firmware file successful! 的本地化字符串。
        /// </summary>
        internal static string String_Write_firmware_file_successful {
            get {
                return ResourceManager.GetString("String_Write_firmware_file_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing air hang data is failed! Error code is 的本地化字符串。
        /// </summary>
        internal static string String_Writing_air_hang_data_is_failed_Error_code_is {
            get {
                return ResourceManager.GetString("String_Writing_air_hang_data_is_failed_Error_code_is", resourceCulture);
            }
        }
    }
}
